sudo: required
services:
  - docker

before_install:
  - docker build -t azraeht/frontend -f Dockerfile.dev .

script:
  - docker run azraeht/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "dockerreact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-3-559213335023"
  bucket_path: "dockerreact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_ACCESS_SECRET